[tool.poetry]
name = "promptdroid"
version = "0.1.0"
description = ""
authors = ["yeus <Thomas.Meschede@web.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.27.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
